name: 'newboy-action'
description: 'Run Postman collections via Newman'
author: 'YeapAi'
branding:
  icon: 'check-square'  
  color: 'orange'
inputs:
  apiKey:
    description: 'Postman API key'
    required: true
  collection:
    description: 'Collection to use'  
  environment: 
    description: 'Environment to use'
runs:
  using: 'node12'
  main: 'index.js'
